{% set version = "0.2.1b" %}

package:
  name: xpressplot
  version: {{ version }}

source:
  url: https://github.com/XPRESSyourself/XPRESSplot/archive/XPRESSplot-v{{ version }}.tar.gz
  sha256: e6d26bb3f43f8bda7ce1465641d835f750b63b31e983cea73143c26e143cc2c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - seaborn
    - plotly <4

test:
  imports:
    - xpressplot

about:
  home: https://github.com/XPRESSyourself/XPRESSplot
  license: GPL-3.0
  license_file: LICENSE
  summary: 'A toolkit for navigating and analyzing gene expression datasets.'
