package:
  name: xpressplot
  version: 0.0.5b

source:
  fn: XPRESSplot-v0.0.5b0.tar.gz
  url: https://github.com/XPRESSyourself/XPRESSplot/archive/XPRESSplot-v0.0.5b0.tar.gz


build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  run:
    - pandas
    - matplotlib
    - numpy
    - plotly
    - seaborn
    - scipy
    - r
    - matplotlib
    - multiqc
    - scikit-learn

about:
  home: https://github.com/XPRESSyourself/XPRESSplot
  license: GPL-3.0
  summary: 'A toolkit for navigating and analyzing gene expression datasets.'
