{% set version = "0.2.3" %}

package:
  name: xpressplot
  version: {{ version }}

source:
  url: https://github.com/XPRESSyourself/XPRESSplot/archive/XPRESSplot-v{{ version }}.tar.gz
  sha256: 7f5d4adbc5448d3e72acb0728f05bbd3d0a728e43ed9886b78c79f62b4b4052a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas<=0.25.3
    - numpy<=1.17.5
    - scipy
    - scikit-learn
    - matplotlib<3.0.0,>=2.1.1
    - seaborn
    - plotly <4

test:
  imports:
    - xpressplot

about:
  home: https://github.com/XPRESSyourself/XPRESSplot
  license: GPL-3.0
  license_file: LICENSE
  summary: 'A toolkit for navigating and analyzing gene expression datasets.'
