language: python

python:
  #- "3.3"
  #- "3.4"
  - "3.5"
  #- "3.5-dev"  # 3.5 development branch
  - "3.6"
  #- "3.6-dev"  # 3.6 development branch
  #- "3.7-dev"  # 3.7 development branch

before_install:

  - git lfs pull

install:

  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install --yes -c anaconda pandas numpy scipy seaborn plotly matplotlib scikit-learn
  - conda install --yes -c gusdunn geoparse

  # You can also install some dependencies with pip if not available in conda

  - git clone https://github.com/XPRESSyourself/XPRESStools.git
  - cd XPRESStools
  - python setup.py install
  - cd ../tests/

script:

  - python fetch_test.py
  - python format_test.py
  #- python analyze_test.py

  #- python interactive_test.py
  #- python normalize_test.py
