language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:

  # Set up a conda environment with the right Python version

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install --yes scikit-learn
  - conda install --yes -c anaconda pandas numpy scipy seaborn plotly matplotlib
  - conda install --yes -c gusdunn geoparse

  # You can also install some dependencies with pip if not available in conda

  - git clone https://github.com/XPRESSyourself/XPRESStools.git
  - cd XPRESStools
  - python setup.py install
  - cd ../

script:

  - python tests/fetch_test.py
  #- python tests/analyze_test.py
  #- python tests/format_test.py
  #- python tests/interactive_test.py
  #- python tests/normalize_test.py
