language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

dist: xenial

before_install:

  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:

  # Install dependencies
  - pip install -r requirements.txt
  - pip install .

  # Install software to test
  - python setup.py install
  - cd tests/

script:

  - python fetch_test.py
  - python format_test.py
  - python normalize_test.py
  #- python analyze_test.py
  #- python interactive_test.py
  #- python other_test.py

after_success:
  #- test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh
