package:
  name: xpressplot
  version: 0.0.4b

source:
  fn: XPRESSplot-0.0.4b2.tar.gz
  url: https://github.com/XPRESSyourself/XPRESSplot/archive/XPRESSplot-0.0.4b2.tar.gz

about:
  home: https://xpressplot.readthedocs.io/en/latest/
  summary: A toolkit for navigating and analyzing gene expression datasets
  license: GPL-3.0
