package:
  name: xpressplot
  version: 0.0.4b

source:
  fn: XPRESSplot-v0.0.4b2.tar.gz
  url: https://github.com/XPRESSyourself/XPRESSplot/archive/XPRESSplot-v0.0.4b2.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - pandas
    - matplotlib
    - numpy
    - plotly
    - seaborn
    - scipy
    - r
    - matplotlib
    - multiqc
    - scikit-learn
